# Homework 1 - Linear Classifiers and Generalizations

In [8]:
import numpy as np
from src import preceptor

## 1. Preceptor Mistakes

In this problem, we will investigate the perceptron algorithm with different iteration ordering.

Consider applying the perceptron algorithm through the origin based on a small training set containing three points:

$x^{(1)}=[-1,-1]$ and $y^{(1)}=1$

$x^{(2)}=[1,0]$	and $y^{(2)}=-1$

$x^{(3)}=[-1, 1.5]$ and $y^{(3)}=1$

Given that the algorithm starts with
, the first point that the algorithm sees is always considered a mistake. The algorithm starts with some data point and then cycles through the data (in order) until it makes no further mistakes. 

In [9]:
def exercise_1_preceptor(
    x: np.ndarray, y: np.ndarray, cycles: int, initial_x_index: int = 0
):
    theta = np.zeros(x.shape[1])
    total_mistakes = 0
    for cycle in range(cycles):
        cycle_mistakes = 0
        for i in range(len(x)):
            if cycle == 0 and i < initial_x_index:
                continue
            if y[i] * np.dot(theta, x[i]) <= 0:
                cycle_mistakes += 1
                total_mistakes += 1
                theta += y[i] * x[i]
            print(f"i: {i}\ttheta: {theta}\ttotal mistakes: {total_mistakes}")
        if not cycle_mistakes:
            return theta
        print("\n")
    return theta

### 1. (a)

#### Question

How many mistakes does the algorithm make until convergence if the algorithm starts with data point $x^{(1)}$? How many mistakes does the algorithm make if it starts with data point $x^{(2)}$? 

Starting with $x^{(1)}$:

In [10]:
x = np.array([[-1, -1], [1, 0], [-1, 1.5]])
y = np.array([1, -1, 1])
exercise_1_preceptor(x, y, cycles=100, initial_x_index=0)

i: 0	theta: [-1. -1.]	total mistakes: 1
i: 1	theta: [-1. -1.]	total mistakes: 1
i: 2	theta: [-2.   0.5]	total mistakes: 2


i: 0	theta: [-2.   0.5]	total mistakes: 2
i: 1	theta: [-2.   0.5]	total mistakes: 2
i: 2	theta: [-2.   0.5]	total mistakes: 2


array([-2. ,  0.5])

Starting with $x^{(2)}$:

In [11]:
x = np.array([[-1, -1], [1, 0], [-1, 1.5]])
y = np.array([1, -1, 1])
exercise_1_preceptor(x, y, cycles=100, initial_x_index=1)

i: 1	theta: [-1.  0.]	total mistakes: 1
i: 2	theta: [-1.  0.]	total mistakes: 1


i: 0	theta: [-1.  0.]	total mistakes: 1
i: 1	theta: [-1.  0.]	total mistakes: 1
i: 2	theta: [-1.  0.]	total mistakes: 1


array([-1.,  0.])

## 2. Preceptor Performance

The following table shows a data set and the number of times each point is misclassified during a run of the perceptron algorithm (with offset ). and are initialized to zero.
	
| i   | x           | y     | times misclassified |
|-----|-------------|-------|---------------------|
| 1   |   [-4, 2]   |   +1  |           1         |
|  2  |   [-2, 1]   |   +1  |           0         |
|  3  |   [-1, -1]  |   -1  |           2         |
|  4  |   [2, 2]    |   -1  |           1         |
|  5  |   [1, -2]   |   -1  |           0         |

In [18]:
def exercise_2_preceptor(
    x: np.ndarray, y: np.ndarray, cycles: int, theta: np.ndarray = None, theta0: float = None
):
    if theta is None:
        theta = np.zeros(x.shape[1])
    if theta0 is None:
        theta0 = 0
    
    misclassified = [0 for _ in range(len(x))]
    for cycle in range(cycles):
        mistakes = 0
        for i in range(len(x)):
            if y[i] * (np.dot(theta, x[i]) + theta0) <= 0:
                mistakes += 1
                theta += y[i] * x[i]
                theta0 += y[i]
                misclassified[i] += 1
            print(f"i: {i+1}\tmisclassified: {misclassified[i]}\ttheta: {theta}\ttheta0: {theta0}")
        print("\n")
    return theta, theta0

### 2. (a)

#### Question

Write down the state of $\theta$ and $\theta_0$ after this run has completed (note, the algorithm may not yet have converged).

#### Answer

In [19]:
x = np.array([[-4, 2], [-2, 1], [-1, -1], [2, 2], [1, -2]])
y = np.array([1, 1, -1, -1, -1])
exercise_2_preceptor(x, y, cycles=3)

i: 1	misclassified: 1	theta: [-4.  2.]	theta0: 1
i: 2	misclassified: 0	theta: [-4.  2.]	theta0: 1
i: 3	misclassified: 1	theta: [-3.  3.]	theta0: 0
i: 4	misclassified: 1	theta: [-5.  1.]	theta0: -1
i: 5	misclassified: 0	theta: [-5.  1.]	theta0: -1


i: 1	misclassified: 1	theta: [-5.  1.]	theta0: -1
i: 2	misclassified: 0	theta: [-5.  1.]	theta0: -1
i: 3	misclassified: 2	theta: [-4.  2.]	theta0: -2
i: 4	misclassified: 1	theta: [-4.  2.]	theta0: -2
i: 5	misclassified: 0	theta: [-4.  2.]	theta0: -2


i: 1	misclassified: 1	theta: [-4.  2.]	theta0: -2
i: 2	misclassified: 0	theta: [-4.  2.]	theta0: -2
i: 3	misclassified: 3	theta: [-3.  3.]	theta0: -3
i: 4	misclassified: 1	theta: [-3.  3.]	theta0: -3
i: 5	misclassified: 0	theta: [-3.  3.]	theta0: -3




(array([-3.,  3.]), -3)

The answer is $\theta = [-4, 2]$ and $\theta_0 = -2$.

### 2. (b)

#### Question

Provide one example of a different initialization of $\theta$ and $\theta_0$ such that the perceptron algorithm with this initialization would not produce any mistakes during a run through the data. 

#### Answer

In [21]:
x = np.array([[-4, 2], [-2, 1], [-1, -1], [2, 2], [1, -2]])
y = np.array([1, 1, -1, -1, -1])
optimal_theta, optimal_theta0 = preceptor.preceptor(x, y, cycles=1000)
exercise_2_preceptor(x, y, cycles=1, theta=optimal_theta, theta0=optimal_theta0)

Optimal theta and theta0 found:  [-3.  3.] -3
i: 1	misclassified: 0	theta: [-3.  3.]	theta0: -3
i: 2	misclassified: 0	theta: [-3.  3.]	theta0: -3
i: 3	misclassified: 0	theta: [-3.  3.]	theta0: -3
i: 4	misclassified: 0	theta: [-3.  3.]	theta0: -3
i: 5	misclassified: 0	theta: [-3.  3.]	theta0: -3




(array([-3.,  3.]), -3)